name: testing dependecy

on:
 push

jobs: 
    ubuntu:
      runs-on: ubuntu-latest
      steps:
         - name: run on ubuntu
           run: date
    windows:
         runs-on: windows-latest
         steps:
             - name: run on windows
               run: date
              
    mac:
       runs-on: macos-latest
       steps: 
          - name: run on maco
            run: date 
    depend:
        needs: [ubuntu, mac]
        runs-on: macos-latest
        steps: 
           - name: make depends
             run: date

