name: testing git action

on:
  push

jobs:
    jobs1:
         name: on ubuntu
         run-on: ubuntu-latest
         steps:
            - name: test run ubuntu
              uses: actions/checkout/v2
              run: env | sort

    jobs2:
         name: on windows
         run-on: windows-latest
         steps:
             - name: test on windows
               uses: actions/checkout/v2
               run:  "Get-ChildItem Env: | Sort-Object Name" 

