name: testing git action

on:
  push

jobs:
    jobs1:
         name: on ubuntu
         runs-on: ubuntu-latest
         steps:
            - name: test run ubuntu
              uses: actions/checkout@v2
            - name: stes 2  
              run: env | sort

    jobs2:
         name: on windows
         runs-on: windows-latest
         steps:
             - name: test on windows
               uses: actions/checkout@v2
             - name: step 2 windows
               run:  "Get-ChildItem Env: | Sort-Object Name" 

